module.exports = {
  loginSuccess: "Login successfully",
  loginFailed: "Login failed",
  invalidPassword: "Password is incorrect",
  userNotFound: "User not found",
  vendorNotFound: "Venfor not found",
  failed: "Your request is not executed.",
  success: "Your request is executed successfully.",
  userDeleted: "user deleted successfully.",
  vendorDeleted: "Vendor deleted successfully.",
  userNotDeleted: "User Deletion Failed.",
  vendorNotDeleted: "Vendor Deletion Failed.",
  userUpdated: "user updated successfully.",
  vendorUpdated: "Vendor updated successfully.",
  unAuthorized: "You are not authorized to perform this action.",
  invalidToken: "Invalid token",
  notFound: "Not Found.",
  alreadyExist: "Data Already exist.",
  inCorrectCred: "Email and password is not correct",
  orderNotFound: "Order not found.",
  productNotFoundInCart: "Product is not present in the cart."
};
